### ISSUE TITLE
Token Invalid

### ISSUE THREAD

**Issue by CracknTea** [Chiitoi/Cherry#3]
Hi, I've been trying to run Cherry for the past few days. I can't manage to get the bot to come online. When I run npm run start this is what is returned:

> cherry@1.3.2 start
> node -r dotenv/config dist/bot.js

C:\Users\Yolo\Downloads\Scrubber\Scrubber\node_modules\discord.js\src\client\Client.js:206
    if (!token || typeof token !== 'string') throw new Error('TOKEN_INVALID');
                                                   ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at CherryClient.login (C:\Users\Yolo\Downloads\Scrubber\Scrubber\node_modules\discord.js\src\client\Client.js:206:52)
    at CherryClient.start (C:\Users\Yolo\Downloads\Scrubber\Scrubber\dist\structures\CherryClient.js:67:20) {
  [Symbol(code)]: 'TOKEN_INVALID'
}

I'm not sure what the problem seems to be since the bot token is valid.

**Comment by jeffreyz29** [comment]
did you put the correct bot token? if you haven't you should reset the bot token and the redo the steps again
